[build]
publish = "static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Security-Policy = "default-src 'none'"
    Content-Security-Policy = "default-src 'none'"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-UA-Compatible = "IE=Edge"
    Cache-Control = "no-cache"

[[headers]]
  for = "*.gif"
  [headers.values]
    Content-Type = "image/gif"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

[[redirects]]
  from = "https://illvart.netlify.com/*"
  to = "https://illvart.pinkyui.com/"
