[build]
publish = "static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "same-origin"
    Cache-Control = "max-age=31536000, immutable"
    Content-Security-Policy = """
      default-src 'none';
      style-src 'self' *.cloudfront.net 'unsafe-inline';
      img-src 'self' https://img.shields.io *.cloudfront.net;
      font-src 'self' *.cloudfront.net;
      script-src https://cdn.jsdelivr.net 'self' 'unsafe-inline' *.cloudfront.net;
      connect-src 'self';
      base-uri 'none';
      upgrade-insecure-requests;
      report-uri https://illvart.report-uri.com/r/d/csp/reportOnly;
    """
    Expect-CT = """
      max-age=0, report-uri="https://illvart.report-uri.com/r/d/csp/reportOnly"
    """
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Accept-Encoding = "gzip, deflate, br"

[[headers]]
  for = "*.gif"
  [headers.values]
    Content-Type = "image/gif"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

[[redirects]]
  from = "https://illvart.netlify.com/*"
  to = "https://illvart.pinkyui.com/"
