[build]
publish = "static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "report-uri https://illvart.report-uri.com/r/d/ct/reportOnly"
    Expect-CT = """
      max-age=0, report-uri="https://illvart.report-uri.com/r/d/ct/reportOnly"
    """
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Accept-Encoding = "gzip, deflate, br"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-cache"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.gif"
  [headers.values]
    Content-Type = "image/gif"
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"
    Cache-Control = "max-age=31536000, immutable"

[[redirects]]
  from = "https://illvart.netlify.com/*"
  to = "https://illvart.pinkyui.com/"
